apiVersion: cloud-run-controller.barpilot.io/v1alpha1
kind: Service
metadata:
  name: example-service
spec:
  project: myProject
  location: us-central1
  service:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    metadata:
      name: service-nginx
    spec:
      runLatest:
        configuration:
          revisionTemplate:
            spec:
              container:
                image: nginx
                resources:
                  limits:
                    memory: 512Mi
              timeoutSeconds: 300
              containerConcurrency: 80
