apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: runservices.cloud-run-controller.barpilot.io
spec:
  group: cloud-run-controller.barpilot.io
  names:
    kind: RunServices
    listKind: RunServicesList
    plural: runservices
    singular: runservices
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
